"""Unit tests for deterministic provenance signals.

These run against synthetic inputs — no git repo needed."""
from collections import Counter

from contrib_estimator.collect.provenance import (
    AI_AUTHOR_RE, AI_FOOTER_RE, AI_FLOW_PATTERNS, COMMITTED_ARTIFACT_RE,
    CONVENTIONAL_RE, EMOJI_AI_RE,
    _burstiness, _human_distribution, _msg_uniformity, _normalize_subject,
)


def test_ai_author_regex_hits():
    for name in ["Alice Agentic", "AliceAgent", "alice-agentic-ops",
                 "Cursor Agent", "Claude Bot", "Devin", "windsurf-bot"]:
        assert AI_AUTHOR_RE.search(name), f"missed: {name}"


def test_ai_author_regex_misses_humans():
    for name in ["Alice", "Bob Smith", "carolm", "Daniela",
                 "Marie Curie", "anon"]:
        assert not AI_AUTHOR_RE.search(name), f"false hit: {name}"


def test_ai_footer_detects_claude():
    body = "feat: add thing\n\nCo-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>"
    assert AI_FOOTER_RE.search(body)


def test_conventional_commits():
    assert CONVENTIONAL_RE.match("feat(api): add endpoint")
    assert CONVENTIONAL_RE.match("fix: handle null")
    assert not CONVENTIONAL_RE.match("Add new feature")


def test_normalize_subject_strips_prefix():
    assert _normalize_subject("feat(allocation-engine): ordina i progetti") == "ordina i progetti"
    assert _normalize_subject("fix: handle null") == "handle null"
    assert _normalize_subject("Update README") == "update readme"


def test_burstiness_zero_for_human_pace():
    # 10 commits spaced 1 hour apart → no <60s gaps
    ts = [3600 * i for i in range(10)]
    assert _burstiness(ts) == 0.0


def test_burstiness_high_for_ai_agent():
    # 10 commits all within 30s of each other → 100%
    ts = [10 * i for i in range(10)]
    assert _burstiness(ts) == 1.0


def test_burstiness_mixed():
    # Half tight, half spread
    ts = [0, 10, 20, 30, 4000, 8000]  # 3 of 5 gaps under 60s
    assert _burstiness(ts) == 3 / 5


def test_msg_uniformity_low_for_diverse():
    subjects = [f"feat: add feature {i}" for i in range(20)]
    # All normalized to unique 3-word subjects → top-5 = 5/20
    assert _msg_uniformity(subjects) == 5 / 20


def test_msg_uniformity_high_for_templated():
    subjects = ["chore: update dependencies"] * 20
    # All identical → top-5 (just 1 unique) = 20/20
    assert _msg_uniformity(subjects) == 1.0


# --- v1 additions: human distribution + AI-flow doc patterns ---

def test_human_distribution_sole_author():
    top, n_sig, _ = _human_distribution(Counter({"alice": 100}))
    assert top == 1.0
    assert n_sig == 1


def test_human_distribution_balanced_team():
    top, n_sig, shares = _human_distribution(
        Counter({"alice": 30, "bob": 25, "carol": 25, "dave": 20})
    )
    assert top == 0.3
    assert n_sig == 4
    assert shares == [0.3, 0.25, 0.25, 0.2]


def test_human_distribution_long_tail_ignored():
    # 1 dominant + 5 trivial (<5% each) → only dominant counts as significant
    top, n_sig, _ = _human_distribution(
        Counter({"alice": 200, **{f"trivial-{i}": 1 for i in range(5)}})
    )
    assert n_sig == 1
    assert top > 0.97


def test_ai_flow_patterns_hit():
    for name in ["ACTION-PLAN.md", "COMPLETION_REPORT.md", "IMPLEMENTATION_PLAN.md",
                 "implementation-progress.md", "HANDOFF.md", "STATUS_UPDATE.md",
                 "MVP_COMPLETE.md", "TEST_REPORT.md", "E2E_TEST_RESULTS.md",
                 "tasks.md", "todo.md", "roadmap.md"]:
        assert AI_FLOW_PATTERNS.match(name), f"missed: {name}"


def test_ai_flow_patterns_miss_normal_docs():
    # CLAUDE.md / AGENTS.md tracked separately as ai_workflow, not research
    for name in ["README.md", "CHANGELOG.md", "LICENSE.md", "CONTRIBUTING.md",
                 "CLAUDE.md", "AGENTS.md", "CODE_OF_CONDUCT.md"]:
        assert not AI_FLOW_PATTERNS.match(name), f"false hit: {name}"


def test_emoji_ai_marker_detected():
    for body in ["🤖 Generated with Claude Code",
                 "✨ all green",
                 "feat: thing\n\nGenerated with Claude",
                 "Generated by AI"]:
        assert EMOJI_AI_RE.search(body), f"missed: {body!r}"


def test_emoji_ai_marker_no_false_positives():
    for body in ["feat: add api", "fix bug", "regular commit message"]:
        assert not EMOJI_AI_RE.search(body), f"false hit: {body!r}"


def test_committed_artifact_patterns():
    for path in [".env", "node_modules/foo.js", "dist/bundle.js",
                 "build/main.o", "app.log", "data.sqlite", "binary.exe",
                 "src/__pycache__/foo.pyc"]:
        assert COMMITTED_ARTIFACT_RE.match(path), f"missed: {path}"


def test_committed_artifact_no_false_positives():
    for path in [".env.example", "src/main.py", "README.md", "tests/test_foo.py"]:
        assert not COMMITTED_ARTIFACT_RE.match(path), f"false hit: {path}"
