"""Repo-wide AI/human provenance signals. Computed once per run, injected as priors.

Signal selection is research-backed:
- Co-Authored-By footers + AI author names: "Fingerprinting AI Coding Agents on GitHub"
  (arxiv 2601.17406, 2025) — commit metadata is more discriminative than code content.
- Commit-message uniformity + conventional-commits compliance: same study.
- Burstiness (inter-commit time variance): humans pause to think; AI runs in tight loops.
- TODO/FIXME density: humans leave debt, AI doesn't ("Debt Behind the AI Boom",
  arxiv 2603.28592).
- Documentation-to-code ratio: AI workflows over-document.
- Multi-signal fusion beats any single signal (TriFusion-LLM, arxiv 2603.15004).
"""
from __future__ import annotations

import re
import subprocess
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

# Author-name patterns that signal AI co-authorship.
# Right-side \b catches CamelCase suffix (e.g. "AliceAgent" → "Agent" at end);
# left-side allows CamelCase prefix.
AI_AUTHOR_RE = re.compile(
    r"(?i)(agent(ic)?[a-z-]*\b|copilot|cursor|claude|chatgpt|codex|aider|"
    r"\bbot\b|ai-?ops?\b|\bllm\b|devin|windsurf)"
)

# Commit-footer co-author markers
AI_FOOTER_RE = re.compile(
    r"(?im)^Co-Authored-By:\s*(Claude|Cursor|Copilot|GPT|Codex|Aider|Devin)"
)

# Conventional commits prefix
CONVENTIONAL_RE = re.compile(
    r"^(feat|fix|chore|refactor|docs|test|style|perf|build|ci)(\([^)]+\))?: "
)

# TODO markers (any language)
TODO_RE = re.compile(r"(?i)\b(TODO|FIXME|XXX|HACK)\b")

# AI signature emojis / markers in commit message bodies. Conservative list —
# Anthropic/Claude Code commits ship the robot emoji + footer; some agentic
# tools include sparkle / lightning emojis in subject lines.
EMOJI_AI_RE = re.compile(
    r"(\U0001F916|🤖|✨|🪄|⚡|generated with claude|generated by ai)",
    re.IGNORECASE,
)

# Files / paths that should NOT be tracked in a healthy repo — their presence
# in git indicates sloppy workflow management (often AI-agent or junior pattern).
COMMITTED_ARTIFACT_RE = re.compile(
    r"(?i)^("
    r"\.env$|\.env\.local$|"           # secrets
    r"node_modules/|"                  # vendored deps
    r"dist/|build/|out/|target/|"      # build artifacts
    r".*\.log$|"                        # log files
    r".*\.sqlite3?$|.*\.db$|"          # local DBs
    r".*\.pyc$|__pycache__/|"          # python bytecode
    r".*\.tar\.gz$|.*\.zip$|"          # archives in src
    r".*\.exe$|.*\.dll$|.*\.so$"       # binaries
    r")"
)

# Files that indicate explicit AI workflow
AI_WORKFLOW_FILES = (
    "CLAUDE.md", "AGENTS.md", ".cursorrules", ".cursor/rules",
    ".github/copilot-instructions.md", ".aider.conf.yml",
    ".claude/", ".windsurfrules",
)


@dataclass
class Provenance:
    total_commits: int
    ai_footer_rate: float          # 0-1: commits with Co-Authored-By AI
    agentic_author_rate: float     # 0-1: commits from AI-named authors
    conventional_rate: float       # 0-1: conventional-commits compliance
    msg_uniformity: float          # 0-1: top-5 normalized subject share
    emoji_ai_rate: float           # 0-1: commits with 🤖/✨ AI markers in body
    avg_body_length: float         # chars: mean body length (excludes subject)
    burstiness: float              # 0-1: fraction of inter-commit gaps under 60s
    peak_commits_per_day: int      # max commits any single calendar day
    distinct_human_authors: int    # authors NOT matching AI pattern
    top_human_share: float         # 0-1: largest single human's commit share
    n_significant_humans: int      # humans contributing >=5% of human commits
    todo_per_kloc: float           # TODO+FIXME+XXX per 1000 LOC
    doc_to_code_ratio: float       # md LOC / code LOC
    has_ai_workflow: bool          # CLAUDE.md / .cursorrules / etc present
    scaffold_score: int            # 0-100: tutorial-scaffold marker sum
    committed_artifacts: int       # tracked files matching "should not be committed" patterns
    ai_prior: int                  # 0-100 derived prior for ai axis
    author_prior: int              # 0-100 derived prior for single-author axis
    team_prior: int                # 0-100 derived prior for team axis
    research_prior: int            # 0-100 derived prior for research axis

    def summary_for_prompt(self) -> str:
        """Compact one-line summary to inject into LLM prompt as repo-level prior."""
        return (
            f"Repo priors: ai_footer={self.ai_footer_rate:.0%}, "
            f"agentic_authors={self.agentic_author_rate:.0%}, "
            f"emoji_ai={self.emoji_ai_rate:.0%}, "
            f"top_human_share={self.top_human_share:.0%}, "
            f"significant_humans={self.n_significant_humans}, "
            f"conventional_commits={self.conventional_rate:.0%}, "
            f"msg_uniformity={self.msg_uniformity:.0%}, "
            f"avg_body_chars={self.avg_body_length:.0f}, "
            f"burstiness={self.burstiness:.2f}, "
            f"peak_commits/day={self.peak_commits_per_day}, "
            f"todo_per_kloc={self.todo_per_kloc:.2f}, "
            f"doc_ratio={self.doc_to_code_ratio:.2f}, "
            f"ai_workflow_files={'yes' if self.has_ai_workflow else 'no'}, "
            f"scaffold_score={self.scaffold_score}, "
            f"committed_artifacts={self.committed_artifacts}"
        )


def _run(args: list[str], cwd: Path) -> str:
    try:
        return subprocess.run(
            ["git", *args], cwd=cwd, capture_output=True, text=True, check=True
        ).stdout
    except subprocess.CalledProcessError:
        return ""


def _commit_signals(repo: Path) -> dict:
    """Walk full log once, collect aggregate signals.

    Format uses %ct (committer unix timestamp) for burstiness, %ad short date
    for daily aggregation, and null-byte field separators with ---END--- record
    sentinel to survive multiline commit bodies.
    """
    out = _run(
        ["log", "--all",
         "--format=%H%x00%an%x00%ae%x00%ad%x00%ct%x00%B%x00---END---",
         "--date=short"],
        repo,
    )
    if not out:
        return {
            "total": 0, "ai_footer": 0, "agentic": 0, "conv": 0,
            "emoji_msgs": 0,
            "by_day": {}, "human_counts": Counter(),
            "timestamps": [], "subjects": [], "body_lengths": [],
        }

    total = ai_footer = agentic = conv = 0
    emoji_msgs = 0
    body_lengths: list[int] = []
    by_day: dict[str, int] = {}
    human_counts: Counter = Counter()
    timestamps: list[int] = []
    subjects: list[str] = []

    for record in out.split("---END---"):
        record = record.strip()
        if not record:
            continue
        parts = record.split("\0", 5)
        if len(parts) < 6:
            continue
        _sha, author, email, date, ts, body = parts
        total += 1
        by_day[date] = by_day.get(date, 0) + 1
        try:
            timestamps.append(int(ts))
        except ValueError:
            pass

        author = author.strip()
        email = email.strip().lower()
        if AI_AUTHOR_RE.search(author) or AI_AUTHOR_RE.search(email):
            agentic += 1
        else:
            # Dedup by email when present (one human often commits under multiple
            # display names sharing one email address). Fall back to name otherwise.
            key = email if "@" in email else author
            human_counts[key] += 1

        if AI_FOOTER_RE.search(body):
            ai_footer += 1
        if EMOJI_AI_RE.search(body):
            emoji_msgs += 1

        subject = body.split("\n", 1)[0]
        subjects.append(subject)
        if CONVENTIONAL_RE.match(subject):
            conv += 1
        # Body length excludes the subject line.
        body_lengths.append(max(0, len(body) - len(subject)))

    return {
        "total": total, "ai_footer": ai_footer, "agentic": agentic,
        "conv": conv, "emoji_msgs": emoji_msgs,
        "by_day": by_day, "human_counts": human_counts,
        "timestamps": timestamps, "subjects": subjects,
        "body_lengths": body_lengths,
    }


def _burstiness(timestamps: list[int]) -> float:
    """Fraction of inter-commit gaps under 60 seconds.

    Tight back-to-back commits are an AI-agent signature (auto-commit-per-edit).
    Humans rarely commit within 60s of the previous commit. This metric is
    robust to long idle periods (unlike CV-based burstiness).
    """
    if len(timestamps) < 3:
        return 0.0
    ts = sorted(timestamps)
    gaps = [ts[i] - ts[i - 1] for i in range(1, len(ts))]
    if not gaps:
        return 0.0
    under_60s = sum(1 for g in gaps if 0 <= g <= 60)
    return under_60s / len(gaps)


# Strip conventional-commit type+scope to extract the verb/topic that follows.
_CONV_STRIP_RE = re.compile(r"^(feat|fix|chore|refactor|docs|test|style|perf|build|ci)(\([^)]+\))?:\s*")


def _normalize_subject(subject: str) -> str:
    """Drop conventional prefix, lowercase, take first 3 words. Captures the
    actual semantic verb of the commit, ignoring the prefix discipline."""
    s = _CONV_STRIP_RE.sub("", subject.strip()).lower()
    return " ".join(s.split()[:3])


def _msg_uniformity(subjects: list[str]) -> float:
    """Top-5 normalized subjects' share of all commits.

    High share = templated/repetitive bodies (AI agent loop signature).
    Conventional-commit prefixes are stripped before counting so the metric
    captures actual semantic repetition, not just `feat:` discipline.
    """
    if not subjects:
        return 0.0
    norms = [_normalize_subject(s) for s in subjects if s.strip()]
    if not norms:
        return 0.0
    counts = Counter(norms)
    top5 = sum(c for _, c in counts.most_common(5))
    return top5 / len(norms)


def _code_doc_loc(repo: Path) -> tuple[int, int, int]:
    """Return (code_loc, doc_loc, todo_count) by scanning tracked files."""
    out = _run(["ls-files"], repo)
    code_exts = (".py", ".ts", ".tsx", ".js", ".jsx", ".java", ".go", ".rs")
    code_loc = doc_loc = todo_count = 0
    for rel in out.splitlines():
        p = repo / rel
        if not p.is_file():
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        lines = text.count("\n") + 1
        if rel.endswith(".md"):
            doc_loc += lines
        elif rel.endswith(code_exts):
            code_loc += lines
            todo_count += len(TODO_RE.findall(text))
    return code_loc, doc_loc, todo_count


def _has_ai_workflow(repo: Path) -> bool:
    return any((repo / name).exists() for name in AI_WORKFLOW_FILES)


def _committed_artifacts(repo: Path) -> int:
    """Count tracked files whose path matches a 'should-not-be-committed' pattern.
    Sloppy git management signal — humans + AI agents both leave these,
    but they're a tell for low-discipline workflow."""
    try:
        out = _run(["ls-files"], repo)
    except subprocess.CalledProcessError:
        return 0
    return sum(1 for rel in out.splitlines() if COMMITTED_ARTIFACT_RE.match(rel))


# Scaffolding files that indicate tutorial/research-derived starter code.
# Each entry is (path-fragment-to-check, points). Points sum into research_prior.
SCAFFOLD_MARKERS = (
    ("alembic", 15),                # SQLAlchemy migration scaffold
    ("manage.py", 15),              # Django scaffold
    (".env.example", 10),
    (".env.sample", 10),
    ("docker-compose.yml", 10),
    ("docker-compose.yaml", 10),
    ("Dockerfile", 5),
    ("Procfile", 5),                # Heroku tutorial
    ("requirements-dev.txt", 5),
    ("Pipfile", 5),
    ("pnpm-workspace.yaml", 5),
    ("nx.json", 5),                 # Nx monorepo scaffold
    ("turbo.json", 5),               # Turborepo scaffold
)

# AI-flow doc patterns — matched as basename (case-insensitive).
# Markdown files agents commonly emit as session artifacts or plans.
# CLAUDE.md / AGENTS.md / .cursorrules are excluded here — they're tracked separately
# as `has_ai_workflow` and only contribute to ai_prior (not research_prior).
AI_FLOW_PATTERNS = re.compile(
    r"(?i)^("
    r"action[-_]?plan|completion[-_]?report|implementation[-_]?(plan|progress)|"
    r"task[-_]?list|tasks|todo|todo[-_].*|"
    r"architecture|design[-_]?doc|"
    r"progress|roadmap|status[-_]?update|"
    r"handoff|hand[-_]?off|"
    r"mvp[-_].*|mvp_complete|"
    r"test[-_]?report|e2e[-_]?test[-_]?results"
    r")\.md$"
)


def _scaffold_score(repo: Path) -> int:
    """Sum of points for present scaffolding files + AI-flow docs + large doc volume."""
    score = 0
    seen: set[str] = set()
    for marker, points in SCAFFOLD_MARKERS:
        key = marker.split(".")[0]
        if key in seen:
            continue
        if (repo / marker).exists():
            score += points
            seen.add(key)

    # AI-flow planning docs: strong indicator the project was scaffolded via agent
    # loops. Scan top 2 directory levels for AI-pattern markdown basenames.
    ai_doc_hits = 0
    for path in repo.glob("*.md"):
        if AI_FLOW_PATTERNS.match(path.name):
            ai_doc_hits += 1
    for path in repo.glob("*/*.md"):
        if AI_FLOW_PATTERNS.match(path.name) and ".git" not in path.parts:
            ai_doc_hits += 1
    score += min(40, ai_doc_hits * 8)

    # README size signal — tutorial-derived projects tend to ship verbose READMEs.
    readme = repo / "README.md"
    if readme.exists():
        try:
            kb = readme.stat().st_size / 1024
            score += min(20, int(kb))
        except OSError:
            pass

    return min(100, score)


def _human_distribution(human_counts: Counter) -> tuple[float, int, list[float]]:
    """Compute (top_share, n_significant, shares) over human authors.

    n_significant = humans contributing >= 5% of human commits.
    """
    if not human_counts:
        return 0.0, 0, []
    total = sum(human_counts.values()) or 1
    shares = sorted((c / total for c in human_counts.values()), reverse=True)
    top_share = shares[0]
    n_significant = sum(1 for s in shares if s >= 0.05)
    return top_share, n_significant, shares


def _compute_priors(
    s: dict, code_loc: int, doc_loc: int, todo_count: int,
    ai_workflow: bool, burstiness: float, msg_uniformity: float,
    scaffold_score: int, top_human_share: float, n_significant: int,
) -> tuple[int, int, int, int]:
    """Derive 0-100 priors (ai, author, team, research) from raw signals.

    Rubric semantics confirmed by 3-repo calibration:
    - `author` = HUMAN-authored proportion (not single-author dominance).
      Treated as anti-AI by default; reduced if no human committers at all.
    - `team` = breadth of human collaboration. Counts significant contributors
      (>=5% share each), capped to dampen long tails of trivial committers.
    - `research` = tutorial-derived/scaffolded share. Detected by presence of
      standard scaffolding files + README size.
    - `ai` = LLM-generated share. Combines explicit metadata (Co-Authored-By,
      agentic author names), workflow files (CLAUDE.md / AGENTS.md), commit
      style signals, and an IDE-Copilot boost when workflow files are present
      but git attribution is silent (Copilot/Cursor in-editor pattern).
    """
    total = max(s["total"], 1)
    ai_footer_rate = s["ai_footer"] / total
    agentic_rate = s["agentic"] / total
    conv_rate = s["conv"] / total
    peak = max(s["by_day"].values()) if s["by_day"] else 0

    todo_per_kloc = (todo_count / max(code_loc, 1)) * 1000
    doc_ratio = doc_loc / max(code_loc, 1)

    explicit_ai = max(ai_footer_rate, agentic_rate)
    ide_copilot_signal = ai_workflow and explicit_ai < 0.25
    emoji_ai_rate = s.get("emoji_msgs", 0) / total

    ai_score = (
        35 * explicit_ai
        + 10 * min(conv_rate, 1.0)
        + 10 * min(peak / 50, 1.0)
        + 20 * (1.0 if ai_workflow else 0.0)
        + 5  * max(0, 1 - todo_per_kloc / 2)
        + 5  * min(doc_ratio, 1.0)
        + 10 * burstiness
        + 5  * min(max(msg_uniformity - 0.2, 0) / 0.6, 1.0)
        + 15 * min(emoji_ai_rate * 4, 1.0)             # 🤖/✨ explicit AI marker — additive
        + (25 if ide_copilot_signal else 0)
    )
    ai_prior = max(0, min(100, round(ai_score)))

    # Author = human-authored share. Anti-correlated with AI when humans exist.
    has_humans = top_human_share > 0.05
    author_prior = max(0, 100 - ai_prior) if has_humans else 0

    # Team = breadth of human collaboration. 1 sig → 0, 2 → 25, 3 → 50, 4+ → 75.
    # Capped at 80 (very large repos with 10+ committers still aren't "perfect" teams).
    team_prior = min(80, max(0, 25 * (n_significant - 1)))

    research_prior = scaffold_score

    return ai_prior, author_prior, team_prior, max(0, min(100, research_prior))


def collect(repo: Path) -> Provenance:
    """Single entry point. Cheap — runs in 1-2 seconds on most repos."""
    s = _commit_signals(repo)
    code_loc, doc_loc, todo_count = _code_doc_loc(repo)
    ai_workflow = _has_ai_workflow(repo)
    burstiness = _burstiness(s["timestamps"])
    msg_uniformity = _msg_uniformity(s["subjects"])
    scaffold_score = _scaffold_score(repo)
    committed_artifacts = _committed_artifacts(repo)

    top_share, n_significant, _ = _human_distribution(s["human_counts"])

    ai_prior, author_prior, team_prior, research_prior = _compute_priors(
        s, code_loc, doc_loc, todo_count, ai_workflow, burstiness, msg_uniformity,
        scaffold_score, top_share, n_significant,
    )

    total = max(s["total"], 1)
    peak = max(s["by_day"].values()) if s["by_day"] else 0
    body_lengths = s.get("body_lengths") or [0]
    avg_body = sum(body_lengths) / len(body_lengths)
    emoji_ai_rate = s.get("emoji_msgs", 0) / total

    return Provenance(
        total_commits=s["total"],
        ai_footer_rate=s["ai_footer"] / total,
        agentic_author_rate=s["agentic"] / total,
        conventional_rate=s["conv"] / total,
        msg_uniformity=msg_uniformity,
        emoji_ai_rate=emoji_ai_rate,
        avg_body_length=avg_body,
        burstiness=burstiness,
        peak_commits_per_day=peak,
        distinct_human_authors=len(s["human_counts"]),
        top_human_share=top_share,
        n_significant_humans=n_significant,
        todo_per_kloc=(todo_count / max(code_loc, 1)) * 1000,
        doc_to_code_ratio=doc_loc / max(code_loc, 1),
        has_ai_workflow=ai_workflow,
        scaffold_score=scaffold_score,
        committed_artifacts=committed_artifacts,
        ai_prior=ai_prior,
        author_prior=author_prior,
        team_prior=team_prior,
        research_prior=research_prior,
    )
